export const objectSymbols = [
    {"symbol": "q"},
    {"symbol": "w"},
    {"symbol": "e"},
    {"symbol": "r"},
    {"symbol": "t"},
    {"symbol": "y"},
    {"symbol": "u"},
    {"symbol": "i"},
    {"symbol": "o"},
    {"symbol": "p"},
    {"symbol": "a"},
    {"symbol": "s"},
    {"symbol": "d"},
    {"symbol": "f"},
    {"symbol": "g"},
    {"symbol": "h"},
    {"symbol": "j"},
    {"symbol": "k"},
    {"symbol": "l"},
    {"symbol": "z"},
    {"symbol": "x"},
    {"symbol": "c"},
    {"symbol": "v"},
    {"symbol": "b"},
    {"symbol": "n"},    
    {"symbol": "m"},
]